/**
 * BomaFlow
 * Module: Authentication
 * File: auth.roles.ts
 *
 * Purpose:
 * Maps every system role to its permissions.
 */

import { PERMISSIONS } from './auth.permissions.js'
import type { AuthRole } from './auth.types.js'
import type { Permission } from './auth.permissions.js'

export const ROLE_PERMISSIONS: Record<
  AuthRole,
  Permission[]
> = {
  tenant: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.LISTING_READ,
    PERMISSIONS.LISTING_SAVE,

    PERMISSIONS.APPLICATION_CREATE,
    PERMISSIONS.APPLICATION_UPDATE,
    PERMISSIONS.APPLICATION_DELETE,

    PERMISSIONS.LEASE_READ,

    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,

    PERMISSIONS.RECEIPT_READ,

    PERMISSIONS.MAINTENANCE_CREATE,
    PERMISSIONS.MAINTENANCE_READ,
  ],

  landlord: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.PROPERTY_CREATE,
    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.PROPERTY_UPDATE,
    PERMISSIONS.PROPERTY_DELETE,

    PERMISSIONS.UNIT_CREATE,
    PERMISSIONS.UNIT_READ,
    PERMISSIONS.UNIT_UPDATE,
    PERMISSIONS.UNIT_DELETE,

    PERMISSIONS.LISTING_CREATE,
    PERMISSIONS.LISTING_UPDATE,
    PERMISSIONS.LISTING_DELETE,
    PERMISSIONS.LISTING_PUBLISH,

    PERMISSIONS.APPLICATION_READ,
    PERMISSIONS.APPLICATION_UPDATE,

    PERMISSIONS.LEASE_CREATE,
    PERMISSIONS.LEASE_READ,
    PERMISSIONS.LEASE_UPDATE,

    PERMISSIONS.PAYMENT_READ,

    PERMISSIONS.MAINTENANCE_ASSIGN,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_UPDATE,

    PERMISSIONS.ANALYTICS_READ,
  ],
  
  manager: [
    PERMISSIONS.PROFILE_READ,
    PERMISSIONS.PROFILE_UPDATE,

    PERMISSIONS.PROPERTY_READ,
    PERMISSIONS.PROPERTY_UPDATE,

    PERMISSIONS.UNIT_READ,
    PERMISSIONS.UNIT_UPDATE,

    PERMISSIONS.LISTING_CREATE,
    PERMISSIONS.LISTING_UPDATE,
    PERMISSIONS.LISTING_PUBLISH,

    PERMISSIONS.APPLICATION_READ,
    PERMISSIONS.APPLICATION_UPDATE,

    PERMISSIONS.LEASE_CREATE,
    PERMISSIONS.LEASE_READ,
    PERMISSIONS.LEASE_UPDATE,

    PERMISSIONS.PAYMENT_READ,

    PERMISSIONS.MAINTENANCE_ASSIGN,
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_UPDATE,

    PERMISSIONS.ANALYTICS_READ,
  ],

  technician: [
    PERMISSIONS.MAINTENANCE_READ,
    PERMISSIONS.MAINTENANCE_UPDATE,

    PERMISSIONS.REPAIR_CREATE,
    PERMISSIONS.REPAIR_UPDATE,
    PERMISSIONS.REPAIR_CLOSE,
  ],

  admin: [
    PERMISSIONS.ADMIN_ALL,
  ],
}